// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcwX-KT87xw-Pq23vkzgOwACenMZ8BHVE',
    appId: '1:441924590452:web:c02f58a6015691c634ea21',
    messagingSenderId: '441924590452',
    projectId: 'flutter-2e7d3',
    authDomain: 'flutter-2e7d3.firebaseapp.com',
    storageBucket: 'flutter-2e7d3.appspot.com',
    measurementId: 'G-F04KFF7JMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjiSGeDWhhCXbaNctOf6mGoJASU-vmnMA',
    appId: '1:441924590452:android:1657b87a951d00a034ea21',
    messagingSenderId: '441924590452',
    projectId: 'flutter-2e7d3',
    storageBucket: 'flutter-2e7d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPI-YPlgWrBpyS2KZTtkVY2DJlGnvYroU',
    appId: '1:441924590452:ios:de5e6a3bd176739a34ea21',
    messagingSenderId: '441924590452',
    projectId: 'flutter-2e7d3',
    storageBucket: 'flutter-2e7d3.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
